import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { Navbar } from "@/components/navbar";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable,
      )}
    >
      <body className="relative min-h-screen w-full overflow-hidden bg-[#08080A]">
        <Image
          src="/logo-ltek-clear.png"
          alt=""
          aria-hidden="true"
          width={500}
          height={500}
          className="pointer-events-none absolute left-1/2 top-1/2 z-0 h-220 w-220 -translate-x-1/2 -translate-y-1/2 object-contain opacity-70 blur-[60px] saturate-150 brightness-110"
        />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
